### ISSUE TITLE
java.net.PortUnreachableException: ICMP Port Unreachable

### ISSUE THREAD

**Issue by madamdata** [git-moss/DrivenByMoss#128]
Bitwig 2.5.1 - Ubuntu Studio 16.04 - TouchOSC Android

The bitwig script console displays this error when connecting (full error below) 
Sending messages from TouchOSC to Bitwig works, but messages from Bitwig to TouchOSC aren't getting through (no flashing on the receive indicator) 
I tried using [udpsend] in Pure Data, and it works there - messages received in TouchOSC. 
Any insight on this? 

--error log---
Could not send UDP message.
java.net.PortUnreachableException: ICMP Port Unreachable
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at com.bitwig.flt.control_surface.opensoundcontrol.d3k.yL2(SourceFile:123)
	at com.bitwig.flt.control_surface.opensoundcontrol.d3k.endBundle(SourceFile:116)
	at de.mossgrabers.bitwig.framework.osc.OpenSoundControlServerImpl.sendBundle(OpenSoundControlServerImpl.java:62)
	at de.mossgrabers.framework.osc.AbstractOpenSoundControlWriter.flush(AbstractOpenSoundControlWriter.java:63)
	at de.mossgrabers.controller.osc.protocol.OSCWriter.flush(OSCWriter.java:190)
	at de.mossgrabers.controller.osc.OSCControllerSetup.lambda$startup$2(OSCControllerSetup.java:138)
	at com.bitwig.flt.control_surface.proxy.BitwigStudioHost$ScheduledTask.invokeCallback(SourceFile:706)
	at vhn.ByR(SourceFile:94)
	at vhn.yL2(SourceFile:90)
	at ZNH.FIu(SourceFile:128)
	at EVY.UfL(SourceFile:76)
	at qdm.NBn(SourceFile:248)
	at va.ByR(SourceFile:298)
	at slC.FIu(SourceFile:217)
	at fv2.run(SourceFile:91)
	at slC.run(SourceFile:102)

**Comment by git-moss** [comment]
Sorry, there is nothing I can do about this. The exception cleary indicates that the port is not reachable. This could have a lot of different reasons on your computer setup / network / access rights.
