### ISSUE TITLE
bitwig OSC crash with MIDI messages

### ISSUE THREAD

**Issue by ovitus** [git-moss/DrivenByMoss#152]
I want to send OSC messages for MIDI notes directly to Bitwig via Jarm's API target setup for Tidalcycles:

-- MIDI
:{
bwMIDITarget = OSCTarget {oName = "BitwigMIDI", oAddress = bwAddress, oPort = bwPort,                               
                          oPath = "/vkb_midi/{channel}/{action}/{value}", oShape = Just [],                         
                          oLatency = bwLatency, oPreamble = bwPreamble, oTimestamp = bwTimestamp}                   
:}

bwMIDI   <- startTidal bwMIDITarget   (defaultConfig {cFrameTimespan = 1/20})

-- oPath parameters
:{
let channel  = pI "channel"
    value    = pF "value"
    action   = pS "action"
:}

let bwV   = streamReplace bwMIDI

I execute this in tidal:
bwV 1 $ channel 1 # action "note" # value 5

but then Bitwig OSC crashes:
**OSC Crashed
For input string: "5.0"**

Any idea why it's crashing with that input string?

**Comment by git-moss** [comment]
I guess it sends a float and not an integer. The path must be, e.g.
/vkb_midi/1/note/5
and not
/vkb_midi/1/note/5.0

Also note that you need to send the velocity as a parameter. E.g.
/vkb_midi/1/note/5.0 127

If this does not help, please post the full stack trace of the exception, which you can find in the script console in Bitwig.

**Comment by ovitus** [comment]
Called init()
Started OSC server on port 8000.
For input string: "10.0"
java.lang.NumberFormatException: For input string: "10.0"
    at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.base/java.lang.Integer.parseInt(Unknown Source)
    at java.base/java.lang.Integer.parseInt(Unknown Source)
    at de.mossgrabers.controller.osc.module.MidiModule.parseMidi(MidiModule.java:147)
    at de.mossgrabers.controller.osc.module.MidiModule.execute(MidiModule.java:70)
    at de.mossgrabers.controller.osc.protocol.OSCParser.handle(OSCParser.java:85)
    at de.mossgrabers.bitwig.framework.daw.HostImpl.lambda$createOSCServer$0(HostImpl.java:177)
    at com.bitwig.flt.control_surface.opensoundcontrol.mcK.PgD(SourceFile:313)
    at com.bitwig.flt.control_surface.opensoundcontrol.mcK.PgD(SourceFile:290)
    at com.bitwig.flt.control_surface.opensoundcontrol.mcK.PgD(SourceFile:300)
    at com.bitwig.flt.control_surface.opensoundcontrol.mcK.PgD(SourceFile:292)
    at com.bitwig.flt.control_surface.opensoundcontrol.Ppt.PgD(SourceFile:121)
    at Gcn.Xav(SourceFile:198)
    at dif.run(SourceFile:91)
    at Gcn.run(SourceFile:102)

Called init()
Started OSC server on port 8000.
Started OSC server on port 8000.
Running.
For input string: "5 127"
java.lang.NumberFormatException: For input string: "5 127"
    at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.base/java.lang.Integer.parseInt(Unknown Source)
    at java.base/java.lang.Integer.parseInt(Unknown Source)
    at de.mossgrabers.controller.osc.module.MidiModule.parseMidi(MidiModule.java:147)
    at de.mossgrabers.controller.osc.module.MidiModule.execute(MidiModule.java:70)
    at de.mossgrabers.controller.osc.protocol.OSCParser.handle(OSCParser.java:85)
    at de.mossgrabers.bitwig.framework.daw.HostImpl.lambda$createOSCServer$0(HostImpl.java:177)
    at com.bitwig.flt.control_surface.opensoundcontrol.mcK.PgD(SourceFile:313)
    at com.bitwig.flt.control_surface.opensoundcontrol.mcK.PgD(SourceFile:290)
    at com.bitwig.flt.control_surface.opensoundcontrol.mcK.PgD(SourceFile:300)
    at com.bitwig.flt.control_surface.opensoundcontrol.mcK.PgD(SourceFile:292)
    at com.bitwig.flt.control_surface.opensoundcontrol.Ppt.PgD(SourceFile:121)
    at Gcn.Xav(SourceFile:198)
    at dif.run(SourceFile:91)
    at Gcn.run(SourceFile:102)

**Comment by ovitus** [comment]
Nevermind, I got it working, had to change something on the Tidalcycles side to get it to be integer

**Comment by git-moss** [comment]
Great.
