### ISSUE TITLE
Auto Color crashed (latest 8.5.1)

### ISSUE THREAD

**Issue by mk-conn** [git-moss/DrivenByMoss#155]
with a java.lang.NullPointerException... 

This is my current config: 

![image](https://user-images.githubusercontent.com/5840922/71728225-c8342f00-2e3c-11ea-866d-a5d4f0664a03.png)

**Comment by git-moss** [comment]
Please post the full exception, you can find it in the script console.

**Comment by mk-conn** [comment]
Oh, didn't know I can find it there :) Here it is: 

```
java.lang.NullPointerException
java.lang.NullPointerException
    at de.mossgrabers.framework.configuration.AbstractConfiguration.<init>(AbstractConfiguration.java:350)
    at de.mossgrabers.controller.autocolor.AutoColorConfiguration.<init>(AutoColorConfiguration.java:45)
    at de.mossgrabers.controller.autocolor.AutoColorSetup.<init>(AutoColorSetup.java:48)
    at de.mossgrabers.bitwig.controller.autocolor.AutoColorExtensionDefinition.getControllerSetup(AutoColorExtensionDefinition.java:38)
    at de.mossgrabers.bitwig.framework.extension.AbstractControllerExtensionDefinition.createInstance(AbstractControllerExtensionDefinition.java:175)
    at bEL.WxC(SourceFile:345)
    at bEL.un(SourceFile:28)
    at HtV.WxC(SourceFile:1134)
    at HtV.un(SourceFile:242)
    at HtV.un(SourceFile:163)
    at HtV.<init>(SourceFile:127)
    at KFR.un(SourceFile:248)
    at KFR.WxC(SourceFile:341)
    at KFR.WxC(SourceFile:198)
    at NNd.run(SourceFile:91)
    at KFR.run(SourceFile:102)


```

**Comment by git-moss** [comment]
Got it. Will be fixed in the next update.
