### ISSUE TITLE
SLMkIII: Crash when re-selecting current track

### ISSUE THREAD

**Issue by texel** [git-moss/DrivenByMoss#160]
On a 61SLMkIII, selecting the current track (which I'm assuming should expand that track's children) instead crashes the script. Here's the log output with backtrace:

```
Called init()
Running.
Firmware version: 350
java.lang.NullPointerException
java.lang.NullPointerException
    at de.mossgrabers.controller.slmkiii.mode.track.AbstractTrackMode.onButton(AbstractTrackMode.java:148)
    at de.mossgrabers.framework.command.trigger.mode.ButtonRowModeCommand.execute(ButtonRowModeCommand.java:51)
    at de.mossgrabers.framework.controller.hardware.AbstractHwButton.handleButtonRelease(AbstractHwButton.java:74)
    at com.bitwig.flt.control_surface.proxy.BitwigStudioHost.lambda$createAction$5(SourceFile:1277)
    at com.bitwig.flt.control_surface.proxy.CustomAction.lambda$invokedByHardwareAction$0(SourceFile:41)
    at itl.KQc(SourceFile:94)
    at itl.mvw(SourceFile:90)
    at LFt.j2S(SourceFile:128)
    at Xsa.IU3(SourceFile:76)
    at yVK.ZdG(SourceFile:248)
    at u2z.KQc(SourceFile:329)
    at pxG.j2S(SourceFile:213)
    at lT3.run(SourceFile:91)
    at pxG.run(SourceFile:102)
```

This seems pretty straightforward, so I'm going to try and bootstrap a dev environment on this machine and see if I can get a PR together, but maybe it'll be a quick fix on your end 😎

**Comment by git-moss** [comment]
This is already fixed. I hope to find time to release the update during the weekend. But thanks!

**Comment by texel** [comment]
@git-moss oh awesome thank you! I looked and didn't see a bug report.

**Comment by git-moss** [comment]
There was none, found it myswlf :-)
