### ISSUE TITLE
apc40 mk2 : Shift+Master button crash if SENDS is active

### ISSUE THREAD

**Issue by laurentdebricon** [git-moss/DrivenByMoss#207]
Switch from PAN mode to SENDS mode,
then Shift+Master produce a crash :

```
Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
    at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
    at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
    at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
    at java.base/java.util.Objects.checkIndex(Unknown Source)
    at java.base/java.util.ArrayList.get(Unknown Source)
    at de.mossgrabers.framework.daw.data.bank.AbstractBank.getItem(AbstractBank.java:51)
    at de.mossgrabers.framework.parameterprovider.SendParameterProvider.get(SendParameterProvider.java:40)
    at de.mossgrabers.framework.mode.AbstractMode.bindControls(AbstractMode.java:480)
    at de.mossgrabers.framework.mode.AbstractMode.parametersAdjusted(AbstractMode.java:193)
    at java.base/java.lang.Iterable.forEach(Unknown Source)
    at de.mossgrabers.framework.parameterprovider.AbstractChannelParameterProvider.notifyParametersObservers(AbstractChannelParameterProvider.java:112)
    at de.mossgrabers.framework.parameterprovider.AbstractChannelParameterProvider.update(AbstractChannelParameterProvider.java:128)
    at de.mossgrabers.framework.parameterprovider.AbstractChannelParameterProvider.update(AbstractChannelParameterProvider.java:25)
    at de.mossgrabers.framework.daw.AbstractModel.lambda$toggleCurrentTrackBank$0(AbstractModel.java:225)
    at java.base/java.lang.Iterable.forEach(Unknown Source)
    at de.mossgrabers.framework.daw.AbstractModel.toggleCurrentTrackBank(AbstractModel.java:225)
    at de.mossgrabers.framework.command.trigger.track.MasterCommand.executeShifted(MasterCommand.java:53)
    at de.mossgrabers.framework.command.core.AbstractTriggerCommand.execute(AbstractTriggerCommand.java:48)
    at de.mossgrabers.framework.controller.hardware.AbstractHwButton.handleButtonPressed(AbstractHwButton.java:70)
    at com.bitwig.flt.control_surface.proxy.CustomAction.lambda$invokedByHardwareAction$0(SourceFile:41)
    at sMH.QUi(SourceFile:94)
    at sMH.i1(SourceFile:90)
    at bIz.TQT(SourceFile:128)
    at OQp.pwn(SourceFile:76)
    at lFQ.VkE(SourceFile:248)
    at FJO.QUi(SourceFile:335)
    at JM.QUi(SourceFile:205)
    at Ski.run(SourceFile:91)
    at JM.run(SourceFile:106)
```

**Comment by git-moss** [comment]
Thanks. Will be fixed in the next update.
