### ISSUE TITLE
APC40 mkI: ColorIndexException when in Drum View

### ISSUE THREAD

**Issue by meburton** [git-moss/DrivenByMoss#223]
The exact circumstances that cause this are unclear to me. So far I've only had it happen when using a Drum Machine device and fooling around with the drum view sequencer. It seems to require more than just entering a couple notes or scrolling around, and I haven't seen it at all in much more extensive playing around with a single Sampler. Changing the color doesn't seem to be part of the deal. Regardless the traceback is similar to this:

`Crash during flush.
de.mossgrabers.framework.controller.color.ColorIndexException: Color for key DAW_COLOR_LIGHT_BROWN is not registered!
	at de.mossgrabers.framework.controller.color.ColorManager.getColorIndex(ColorManager.java:80)
	at de.mossgrabers.framework.controller.grid.PadGridImpl.lightEx(PadGridImpl.java:130)
	at de.mossgrabers.framework.controller.grid.PadGridImpl.lightEx(PadGridImpl.java:114)
	at de.mossgrabers.framework.view.AbstractDrumView.drawSequencerSteps(AbstractDrumView.java:669)
	at de.mossgrabers.framework.view.AbstractDrumView.drawSequencerSteps(AbstractDrumView.java:642)
	at de.mossgrabers.framework.view.AbstractDrumView.drawGrid(AbstractDrumView.java:357)
	at de.mossgrabers.framework.controller.AbstractControlSurface.updateGrid(AbstractControlSurface.java:1016)
	at de.mossgrabers.framework.controller.AbstractControlSurface.flushHandler(AbstractControlSurface.java:704)
	at de.mossgrabers.framework.controller.AbstractControlSurface.lambda$scheduleTask$9(AbstractControlSurface.java:911)
	at com.bitwig.flt.control_surface.proxy.BitwigStudioHost$ScheduledTask.invokeCallback(SourceFile:715)
`

The framework parts of the drum view roughly seem to get an RGB color from the Bitwig API then translate it to an internal representation, which in the error state is always one beginning "DAW_COLOR" that's only registered for the mkII. I didn't attempt to fully understand all that code, but I changed the constructor in the APC's DrumView to provide `surface.isMkII ()` instead of `true` for the useDawColors argument to the superclass's constructor and haven't encountered the issue since. I really have no idea if that's the right solution or not.

I first encountered the issue on a build with minor unrelated modifications but also reproed it with 10.9.5.

**Comment by git-moss** [comment]
Referenced the wrong issue.

**Comment by git-moss** [comment]
Thanks!
