### ISSUE TITLE
Flexi Bitwig Linux : no file selection dialog opening

### ISSUE THREAD

**Issue by Llamatron2112** [git-moss/DrivenByMoss#229]
I don't get any file selection dialog when clicking either Save or Load buttons in the Flexi settings. I tested in Gnome with Arch and XFCE with Void, Bitwig 3.3.1 and DBM 11.5.1

**Comment by git-moss** [comment]
It's a bit hidden but explained in section 10.0.1:

Linux: If the file dialogs to save/load do not work make sure you have zenity installed. To install zenity from the command line enter: sudo apt install zenity

**Comment by Llamatron2112** [comment]
Well I do have zenity installed on both installs

**Comment by git-moss** [comment]
Hmm, no real idea. Have tried opening a dialog with zenity from the command line? Could be that some library is missing.

**Comment by Llamatron2112** [comment]
Yes, zenity --file-selection spawns a file selection dialog, which returns the full path to the file I have selected

**Comment by git-moss** [comment]
Do you see any error in the either the JavaScript console or the Bitwig log file?
You could try to run Bitwig as root to see if this is somehow a security issue.

**Comment by Llamatron2112** [comment]
Running as root didn't make it work, but with less spam than on an install where it scans plenty stuff I could see a java exception around when the UI is finished loading : 

```
[2021-01-24 14:26:48 windowing-system-core error] :
	java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Unknown Source)
	at com.bitwig.windowing_system.Display.DIA(SourceFile:641)
	at cPn.iMF(SourceFile:693)
	at cPr.run(SourceFile:616)
	at cPn.aUC(SourceFile:638)
	at cPp.run(SourceFile:582)
```
and I didn't know about the javascript console but there is another exception when clicking the save or load buttons : 
```
Called init()
Running.
No file name set.
Could not create file dialog.
java.io.IOException: Please install zenity from the command line: 'sudo apt install zenity'
	at de.mossgrabers.nativefiledialogs.linux.NativeLinuxFileDialogs.selectFile(NativeLinuxFileDialogs.java:67)
	at de.mossgrabers.nativefiledialogs.linux.NativeLinuxFileDialogs.selectNewFile(NativeLinuxFileDialogs.java:51)
	at de.mossgrabers.controller.generic.controller.GenericFlexiControlSurface.getFileName(GenericFlexiControlSurface.java:324)
	at de.mossgrabers.controller.generic.controller.GenericFlexiControlSurface.saveFile(GenericFlexiControlSurface.java:283)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at de.mossgrabers.framework.configuration.AbstractConfiguration.notifyObservers(AbstractConfiguration.java:1454)
	at de.mossgrabers.controller.generic.GenericFlexiConfiguration.lambda$init$2(GenericFlexiConfiguration.java:384)
	at de.mossgrabers.bitwig.framework.configuration.SignalSettingImpl.lambda$addSignalObserver$0(SignalSettingImpl.java:41)
	at com.bitwig.flt.control_surface.values.SignalProxy.notifyObservers(SourceFile:121)
	at Adx.DIA(SourceFile:94)
	at Adx.YCb(SourceFile:90)
	at QO3.iMF(SourceFile:128)
	at CAN.TUf(SourceFile:76)
	at nyy.FQx(SourceFile:273)
	at iun.DIA(SourceFile:329)
	at Gtr.DIA(SourceFile:205)
	at KbG.run(SourceFile:91)
	at Gtr.run(SourceFile:106)

Could not create file dialog.
java.io.IOException: Please install zenity from the command line: 'sudo apt install zenity'
	at de.mossgrabers.nativefiledialogs.linux.NativeLinuxFileDialogs.selectFile(NativeLinuxFileDialogs.java:67)
	at de.mossgrabers.nativefiledialogs.linux.NativeLinuxFileDialogs.selectFile(NativeLinuxFileDialogs.java:42)
	at de.mossgrabers.controller.generic.controller.GenericFlexiControlSurface.getFileName(GenericFlexiControlSurface.java:324)
	at de.mossgrabers.controller.generic.controller.GenericFlexiControlSurface.loadAndSelectFile(GenericFlexiControlSurface.java:244)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at de.mossgrabers.framework.configuration.AbstractConfiguration.notifyObservers(AbstractConfiguration.java:1454)
	at de.mossgrabers.controller.generic.GenericFlexiConfiguration.lambda$init$3(GenericFlexiConfiguration.java:385)
	at de.mossgrabers.bitwig.framework.configuration.SignalSettingImpl.lambda$addSignalObserver$0(SignalSettingImpl.java:41)
	at com.bitwig.flt.control_surface.values.SignalProxy.notifyObservers(SourceFile:121)
	at Adx.DIA(SourceFile:94)
	at Adx.YCb(SourceFile:90)
	at QO3.iMF(SourceFile:128)
	at CAN.TUf(SourceFile:76)
	at nyy.FQx(SourceFile:273)
	at iun.DIA(SourceFile:329)
	at Gtr.DIA(SourceFile:205)
	at KbG.run(SourceFile:91)
	at Gtr.run(SourceFile:106)
```
This is after just clicking save then load, seems twice the same error but maybe I miss some important info like a line number or something

**Comment by git-moss** [comment]
The exceptions only mean that the zenity command could not be started but give no hint about why. I also looked around a bit about possible causes but couldn't find anything helpful. Sorry.

**Comment by patlach42** [comment]
Have same error with various zenity versions. On Manjaro linux with Bitwig 3.3.1

**Comment by KottV** [comment]
I'd like to debug this issue , but see no `nativefilechooser` sources here.

**Comment by git-moss** [comment]
Just made it public for you: https://github.com/git-moss/NativeFileDialogs
But I am afraid there is not much to debug since it simply calls zenity and it works or not. But good luck :-) Would also be great if you could implement a better solution than zenity...

**Comment by KottV** [comment]
thanks:)

**Comment by KottV** [comment]
I can say that for me (openSUSE) `zenity` invokes with that method https://stackoverflow.com/questions/33878802/zenity-bash-command-not-working-with-java
and i have to comment this lines, dunno why it fails:
https://github.com/git-moss/NativeFileDialogs/blob/12175c85d60bfb51903557b48d6e4524ab00d6a7/src/main/java/de/mossgrabers/nativefiledialogs/linux/NativeLinuxFileDialogs.java#L66

```        
if (!isZenityPresent)
throw new IOException ("Please install zenity from the command line: 'sudo apt install zenity'");
```

**Comment by git-moss** [comment]
> 
> 
> I can say that for me (openSUSE) `zenity` invokes with that method https://stackoverflow.com/questions/33878802/zenity-bash-command-not-working-with-java
> and i have to comment these lines, dunno why it fails:
> https://github.com/git-moss/NativeFileDialogs/blob/12175c85d60bfb51903557b48d6e4524ab00d6a7/src/main/java/de/mossgrabers/nativefiledialogs/linux/NativeLinuxFileDialogs.java#L66
> 
> ```
> if (!isZenityPresent)
> throw new IOException ("Please install zenity from the command line: 'sudo apt install zenity'");
> ```

Then you would need to check why the detectZenity() call fails (which zenity...).

**Comment by KottV** [comment]
It doesn't fails, it returns the proper path.
But that condition does: `if (!isZenityPresent)`
Could it be modified outside of instansc due the `static`? Sorry, I'm a zero in Java :)

**Comment by git-moss** [comment]
> 
> 
> It doesn't fails, it returns the proper path.
> But that condition does: `if (!isZenityPresent)`
> Could it be modified outside of instansc due the `static`? Sorry, I'm a zero in Java :)

I checked in a new version which removed the static, since it does not really make sense. But it should not have an effect.

**Comment by KottV** [comment]
I found the problem. Ubuntu uses `which` from the Debian's sef-made package: https://salsa.debian.org/debian/debianutils
Others distros uses https://savannah.gnu.org/projects/which

and gnu `which` throws an error from Java's process on `2>/dev/null`:
`which: no null in (./2 >/dev)`
while it works fine in command line

so I changed this https://github.com/git-moss/NativeFileDialogs/blob/0a7ca3207b7679c044f69e5857db830bc8ec58b5/src/main/java/de/mossgrabers/nativefiledialogs/AbstractNativeFileDialogs.java#L131 and it started to work:
```
        final String err = error.toString ().trim ();
        if (!err.isEmpty ())
            System.out.println(err);
            //throw new IOException (err);
```

**Comment by git-moss** [comment]
> I found the problem. Ubuntu uses `which` from the Debian's sef-made package: https://salsa.debian.org/debian/debianutils
> Others distros uses https://savannah.gnu.org/projects/which
> 
> and gnu `which` throws an error from Java's process on `2>/dev/null`:
> `which: no null in (./2 >/dev)`

Thanks for pointing me in the right direction! Who would have guessed that there are 2 versions of "which", which work differently :-)

I switched now to checking the exit code, which should work fine with both versions. Can you please check?
I also checked in a new version of DrivenByMoss with the fix, if you want to check that, too.

**Comment by KottV** [comment]
Great, cool!
I did a brief test and all worked. I'll ask other guys do couple test of that build also.

**Comment by KottV** [comment]
Yes it works.
Thank You!
