### ISSUE TITLE
Bug: Adding a new track to an empty Bitwig project with Push 2 crashes extension

### ISSUE THREAD

**Issue by tonybyrne** [git-moss/DrivenByMoss#245]
To reproduce:

* Open Bitwig, using a template containing NO tracks, or delete all existing tracks
* Press "Add Track" on Push 2
* Select any type of track to add

The extension then crashes with the following:

<img width="290" alt="Screenshot 2021-05-08 at 11 49 22" src="https://user-images.githubusercontent.com/27082/117536551-88aec180-aff3-11eb-905b-7e9afafb1265.png">

This affects the current version (v11.8.0) but was present in at least one earlier version.

**Comment by tonybyrne** [comment]
Sure! See below. I forgot to mention that I'm on the latest version of Bitwig (v3.3.7) on a Mac. Also, thank you for what must have been a huge effort to create and maintain the extension.

```
java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
    at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
    at java.base/java.util.HashMap$KeyIterator.next(Unknown Source)
    at de.mossgrabers.framework.daw.data.bank.AbstractBank.lambda$notifySelectionObservers$0(AbstractBank.java:121)
    at com.bitwig.flt.control_surface.proxy.BitwigStudioHost$ScheduledTask.invokeCallback(SourceFile:716)
    at XN.WHD(SourceFile:94)
    at XN.Ycy(SourceFile:90)
    at GRU.YOT(SourceFile:128)
    at isx.aUC(SourceFile:76)
    at Kpo.od(SourceFile:273)
    at Wby.WHD(SourceFile:329)
    at QWh.WHD(SourceFile:205)
    at kIU.run(SourceFile:91)
    at QWh.run(SourceFile:106)
```

**Comment by git-moss** [comment]
Could you please check if this fixes the issue: http://mossgrabers.de/stuff/DrivenByMoss-syncfix.zip

**Comment by tonybyrne** [comment]
Unfortunately, it doesn't, but the stack trace is slightly different with respect to line numbers.

```
java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
    at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
    at java.base/java.util.HashMap$KeyIterator.next(Unknown Source)
    at de.mossgrabers.framework.daw.data.bank.AbstractBank.lambda$notifySelectionObservers$0(AbstractBank.java:121)
    at com.bitwig.flt.control_surface.proxy.BitwigStudioHost$ScheduledTask.invokeCallback(SourceFile:716)
    at XN.WHD(SourceFile:94)
    at XN.Ycy(SourceFile:90)
    at GRU.YOT(SourceFile:128)
    at isx.aUC(SourceFile:76)
    at Kpo.od(SourceFile:273)
    at Wby.WHD(SourceFile:329)
    at QWh.WHD(SourceFile:205)
    at kIU.run(SourceFile:91)
    at QWh.run(SourceFile:106)
```

**Comment by git-moss** [comment]
This is the old version you are running.

**Comment by tonybyrne** [comment]
> This is the old version you are running.

Apologies, I copied the wrong stack trace. I verified that I am using the syncfix version you shared above.

```
java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
    at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
    at java.base/java.util.HashMap$KeyIterator.next(Unknown Source)
    at de.mossgrabers.framework.daw.data.bank.AbstractBank.lambda$0(AbstractBank.java:135)
    at com.bitwig.flt.control_surface.proxy.BitwigStudioHost$ScheduledTask.invokeCallback(SourceFile:716)
    at XN.WHD(SourceFile:94)
    at XN.Ycy(SourceFile:90)
    at GRU.YOT(SourceFile:128)
    at isx.aUC(SourceFile:76)
    at Kpo.od(SourceFile:273)
    at Wby.WHD(SourceFile:329)
    at QWh.WHD(SourceFile:205)
    at kIU.run(SourceFile:91)
    at QWh.run(SourceFile:106)

**Comment by git-moss** [comment]
Tricky one. This should now really fix it: http://mossgrabers.de/stuff/DrivenByMoss-syncfix2.zip

**Comment by tonybyrne** [comment]
It does! :-) Working flawlessly now. Thanks again for this brilliant extension and for the quick responses.

**Comment by git-moss** [comment]
Great!
