### ISSUE TITLE
OSC: aftertouch crashes the plugin

### ISSUE THREAD

**Issue by kdejaeger** [git-moss/DrivenByMoss#45]
On a polysynth and using the aftertouch url ( /vkb_midi/{Channel:0-16}/aftertouch/{Note:0-127} {Pressure:0-127} ), the last note pressed keeps playingn and the extension crashes.

**Comment by git-moss** [comment]
Can you please send the stacktrace of the crash (from the Bitwig script console)? I cannot reproduce that.

**Comment by kdejaeger** [comment]
```
OSC: dispatching message: /vkb_midi/0/note/58(,f)
OSC:    !!! no method handler for the previous message
OSC: dispatching message: /vkb_midi/0/note/58(,f)
OSC:    !!! no method handler for the previous message
OSC: dispatching message: /vkb_midi/0/note/57(,f)
OSC:    !!! no method handler for the previous message
OSC: dispatching message: /vkb_midi/0/aftertouch(,f)
OSC:    !!! no method handler for the previous message
java.util.NoSuchElementException
java.util.NoSuchElementException
    at java.util.LinkedList.removeFirst(LinkedList.java:270)
    at de.mossgrabers.osc.protocol.OSCParser.parseMidi(OSCParser.java:1196)
    at de.mossgrabers.osc.protocol.OSCParser.handle(OSCParser.java:483)
    at com.bitwig.flt.control_surface.opensoundcontrol.eBI.UBy(SourceFile:316)
    at com.bitwig.flt.control_surface.opensoundcontrol.eBI.UBy(SourceFile:293)
    at com.bitwig.flt.control_surface.opensoundcontrol.Wpn.UBy(SourceFile:109)
    at YRz.aH(SourceFile:237)
    at QEu.run(SourceFile:91)
    at YRz.run(SourceFile:106)
```

```

  args: [ { type: 'f', value: 74.68 } ] } To : 127.0.0.1:8000
OSC sent:  { address: '/vkb_midi/0/note/57',
  args: [ { type: 'f', value: 0 } ] } To : 127.0.0.1:8000
OSC sent:  { address: '/vkb_midi/0/note/58',
  args: [ { type: 'f', value: 127 } ] } To : 127.0.0.1:8000
OSC sent:  { address: '/vkb_midi/0/aftertouch',
  args: [ { type: 'f', value: 73.96 } ] } To : 127.0.0.1:8000
OSC sent:  { address: '/vkb_midi/0/aftertouch',
  args: [ { type: 'f', value: 73.6 } ] } To : 127.0.0.1:8000
OSC sent:  { address: '/vkb_midi/0/aftertouch',
  args: [ { type: 'f', value: 73.24 } ] } To : 127.0.0.1:8000
OSC sent:  { address: '/vkb_midi/0/note/58',
```

[open_stage_control_bitwig.zip](https://github.com/git-moss/DrivenByMoss/files/1786740/open_stage_control_bitwig.zip)

**Comment by git-moss** [comment]
This is Poly aftertouch, so you need to give the note. However, I should prevent the crash.
E.g. /vkb_midi/0/aftertouch/65

**Comment by kdejaeger** [comment]
Ok.
I'll ask for a osc 'split' property on the open stage control fader to it can send /aftertouch/integer

**Comment by git-moss** [comment]
You can already send integer if you set the precision to 0.

**Comment by kdejaeger** [comment]
The issue is that open stage control cannot send yet /atertouch/a_value but it sends it as a argument instead, which crashed it.

**Comment by kdejaeger** [comment]
Can you instead make it possible to send the note as an argument, a value to /aftertouch ?

**Comment by git-moss** [comment]
Yes, will look into this but dont have time before the weekend.

**Comment by git-moss** [comment]
If the note misses the message will trigger channel aftertouch in the next version.
