### ISSUE TITLE
OSC crash at /track/+

### ISSUE THREAD

**Issue by kdejaeger** [git-moss/DrivenByMoss#50]
When the selected track is 8, and you do /track/+ 

java.lang.ArrayIndexOutOfBoundsException: 8
    at de.mossgrabers.framework.daw.AbstractChannelBank.getTrack(AbstractChannelBank.java:93)
    at de.mossgrabers.osc.protocol.OSCParser.parseTrackCommands(OSCParser.java:723)
    at de.mossgrabers.osc.protocol.OSCParser.handle(OSCParser.java:229)
    at com.bitwig.flt.control_surface.opensoundcontrol.BQr.HBU(SourceFile:316)
    at com.bitwig.flt.control_surface.opensoundcontrol.BQr.HBU(SourceFile:293)
    at com.bitwig.flt.control_surface.opensoundcontrol.hzb.HBU(SourceFile:109)
    at QYT.faG(SourceFile:237)
    at ti1.run(

**Comment by kdejaeger** [comment]
Should probably do the same as /track/bank/page/+ in that case.

**Comment by git-moss** [comment]
Seems a line got lost :-) Will be fixed in next update!
