### ISSUE TITLE
lates version of oscillator template mixer page seems corrupted or missing main channel strip 

### ISSUE THREAD

**Issue by Sebastian-blu** [git-moss/DrivenByMoss#70]
hey I was just checking your latest open stage template to see how you implemented the touched fader commands but the latest template is missing a the main fader that all the clones are built from or. I tried re downloading it to no avail. 

![screenshot_2018-05-30 17 38 30_phsdub](https://user-images.githubusercontent.com/28813706/40754862-54113776-6430-11e8-8a2d-fc7f00730725.png)

here is the error message from openStage

[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)
[Renderer process error]
Uncaught ReferenceError: isArray is not defined
at isArray (src/browser/js/app/widgets/common/osc-receiver.js:33:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at emitEvent (src/browser/js/app/events/event-emitter.js:27:8)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at String (src/browser/js/app/osc.js:52:13)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at getListeners (node_modules/wolfy87-eventemitter/EventEmitter.js:1:0)
at Array.isArray (src/browser/js/app/ipc/index.js:107:21)

**Comment by jean-emmanuel** [comment]
This particular error in o-s-c should be fixed in v0.32.1 ;)
