### ISSUE TITLE
OSC4Bitwig crash in 2.4 beta 1&2

### ISSUE THREAD

**Issue by JohannesTress** [git-moss/DrivenByMoss#82]
If I try to launch the OSC4Bitwig Script in the latest beta, I get the following error: 

"OSC4Bitwig crashed com.bitwig.extension.controller.api ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;"

Restart won't work, the only chance is to disable the script.

**Comment by git-moss** [comment]
See here: https://github.com/git-moss/DrivenByMoss/issues/80

**Comment by JohannesTress** [comment]
Hi Moss and thanks a lot, I did try to use your latest beta, but now I get a crash whenever I play a note via open stage control. Bitwig tells me "OSC crashed java.lang.NullPointerException"

**Comment by git-moss** [comment]
Can you please post the whole exception from the script console?

**Comment by JohannesTress** [comment]
```
Called init()
Initialized.
Could not send UDP message.
java.net.PortUnreachableException: ICMP Port Unreachable
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at com.bitwig.flt.control_surface.opensoundcontrol.JKl.LIa(SourceFile:123)
	at com.bitwig.flt.control_surface.opensoundcontrol.JKl.endBundle(SourceFile:116)
	at de.mossgrabers.bitwig.framework.osc.OpenSoundControlServerImpl.sendBundle(OpenSoundControlServerImpl.java:64)
	at de.mossgrabers.framework.osc.AbstractOpenSoundControlWriter.flush(AbstractOpenSoundControlWriter.java:61)
	at de.mossgrabers.controller.osc.protocol.OSCWriter.flush(OSCWriter.java:181)
	at de.mossgrabers.controller.osc.OSCControllerSetup.flush(OSCControllerSetup.java:56)
	at de.mossgrabers.bitwig.framework.extension.GenericControllerExtension.flush(GenericControllerExtension.java:59)
	at pdf.VGb(SourceFile:31)
	at Zsv.bUw(SourceFile:263)
	at jwj.nk1(SourceFile:81)
	at Zsv.Ovp(SourceFile:248)
	at LNJ.EmU(SourceFile:298)
	at Ygk.eXt(SourceFile:217)
	at lx3.run(SourceFile:91)
	at Ygk.run(SourceFile:102)

java.lang.NullPointerException
java.lang.NullPointerException
    at de.mossgrabers.controller.osc.protocol.OSCParser.parseMidi(OSCParser.java:1539)
    at de.mossgrabers.controller.osc.protocol.OSCParser.handle(OSCParser.java:258)
    at de.mossgrabers.bitwig.framework.daw.HostImpl.lambda$createOSCServer$0(HostImpl.java:167)
    at com.bitwig.flt.control_surface.opensoundcontrol.OPS.EmU(SourceFile:317)
    at com.bitwig.flt.control_surface.opensoundcontrol.OPS.EmU(SourceFile:294)
    at com.bitwig.flt.control_surface.opensoundcontrol.dMJ.EmU(SourceFile:108)
    at Ygk.eXt(SourceFile:202)
    at lx3.run(SourceFile:91)
    at Ygk.run(SourceFile:102)
```

**Comment by git-moss** [comment]
Are you sure you are running Beta 3 of DrivenByMoss? From the NullPointerException it looks like you are running the old one.

**Comment by JohannesTress** [comment]
Yes, I tried to reinstall it again into an emtpy "extensions" folder and it gave me the exact same error again. The controller-settings in the dashboard are reporting "DrivenByMoss by Jürgen Moßgraber v6.00"

**Comment by git-moss** [comment]
I think I found it. Please look into the KVR thread to download Beta 4.

**Comment by JohannesTress** [comment]
Wow, this was fast! Thanks indeed for your great work and keep up with it...
