### ISSUE TITLE
APC mini extension crashes in Bitwig 2.4 beta2

### ISSUE THREAD

**Issue by klingtnet** [git-moss/DrivenByMoss#83]
I build the extension from the most recent master, i.e. a47a56a371c77c12c076d5b9e7e65c3b942a916e .
Here are the stack-traces from Bitwig's log:

```sh
[2018-08-08 23:08:38 float-gui-widgets error] :
	java.lang.NoSuchMethodError: com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
	at de.mossgrabers.bitwig.framework.daw.data.SlotImpl.<init>(SlotImpl.java:43)
	at de.mossgrabers.bitwig.framework.daw.data.TrackImpl.<init>(TrackImpl.java:62)
	at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.createTracks(AbstractTrackBankImpl.java:219)
	at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.init(AbstractTrackBankImpl.java:47)
	at de.mossgrabers.bitwig.framework.daw.TrackBankImpl.<init>(TrackBankImpl.java:50)
	at de.mossgrabers.bitwig.framework.daw.ModelImpl.<init>(ModelImpl.java:74)
	at de.mossgrabers.bitwig.framework.BitwigSetupFactory.createModel(BitwigSetupFactory.java:44)
	at de.mossgrabers.controller.apcmini.APCminiControllerSetup.createModel(APCminiControllerSetup.java:94)
	at de.mossgrabers.framework.controller.AbstractControllerSetup.init(AbstractControllerSetup.java:105)
	at de.mossgrabers.bitwig.framework.extension.GenericControllerExtension.init(GenericControllerExtension.java:42)
	at pdf.jwg(SourceFile:19)
	at Zsv.LIa(SourceFile:57)
	at LNJ.Jt2(SourceFile:237)
	at LNJ.EmU(SourceFile:164)
	at LNJ.<init>(SourceFile:127)
	at Ygk.EmU(SourceFile:251)
	at Ygk.eXt(SourceFile:343)
	at Ygk.eXt(SourceFile:202)
	at lx3.run(SourceFile:91)
	at Ygk.run(SourceFile:102)

[2018-08-08 23:08:38 float-gui-widgets error] :
	java.lang.NoSuchMethodError: com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
	at de.mossgrabers.bitwig.framework.daw.data.SlotImpl.<init>(SlotImpl.java:43)
	at de.mossgrabers.bitwig.framework.daw.data.TrackImpl.<init>(TrackImpl.java:62)
	at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.createTracks(AbstractTrackBankImpl.java:219)
	at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.init(AbstractTrackBankImpl.java:47)
	at de.mossgrabers.bitwig.framework.daw.TrackBankImpl.<init>(TrackBankImpl.java:50)
	at de.mossgrabers.bitwig.framework.daw.ModelImpl.<init>(ModelImpl.java:74)
	at de.mossgrabers.bitwig.framework.BitwigSetupFactory.createModel(BitwigSetupFactory.java:44)
	at de.mossgrabers.controller.apcmini.APCminiControllerSetup.createModel(APCminiControllerSetup.java:94)
	at de.mossgrabers.framework.controller.AbstractControllerSetup.init(AbstractControllerSetup.java:105)
	at de.mossgrabers.bitwig.framework.extension.GenericControllerExtension.init(GenericControllerExtension.java:42)
	at pdf.jwg(SourceFile:19)
	at Zsv.LIa(SourceFile:57)
	at LNJ.Jt2(SourceFile:237)
	at LNJ.EmU(SourceFile:164)
	at LNJ.<init>(SourceFile:127)
	at Ygk.EmU(SourceFile:251)
	at Ygk.eXt(SourceFile:343)
	at Ygk.eXt(SourceFile:202)
	at lx3.run(SourceFile:91)
	at Ygk.run(SourceFile:102)

[2018-08-08 23:08:38 float-gui-widgets error] :
	java.lang.NoSuchMethodError: com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
	at de.mossgrabers.bitwig.framework.daw.data.SlotImpl.<init>(SlotImpl.java:43)
	at de.mossgrabers.bitwig.framework.daw.data.TrackImpl.<init>(TrackImpl.java:62)
	at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.createTracks(AbstractTrackBankImpl.java:219)
	at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.init(AbstractTrackBankImpl.java:47)
	at de.mossgrabers.bitwig.framework.daw.TrackBankImpl.<init>(TrackBankImpl.java:50)
	at de.mossgrabers.bitwig.framework.daw.ModelImpl.<init>(ModelImpl.java:74)
	at de.mossgrabers.bitwig.framework.BitwigSetupFactory.createModel(BitwigSetupFactory.java:44)
	at de.mossgrabers.controller.apcmini.APCminiControllerSetup.createModel(APCminiControllerSetup.java:94)
	at de.mossgrabers.framework.controller.AbstractControllerSetup.init(AbstractControllerSetup.java:105)
	at de.mossgrabers.bitwig.framework.extension.GenericControllerExtension.init(GenericControllerExtension.java:42)
	at pdf.jwg(SourceFile:19)
	at Zsv.LIa(SourceFile:57)
	at LNJ.Jt2(SourceFile:237)
	at LNJ.EmU(SourceFile:164)
	at LNJ.<init>(SourceFile:127)
	at Ygk.EmU(SourceFile:251)
	at Ygk.eXt(SourceFile:343)
	at Ygk.eXt(SourceFile:202)
	at lx3.run(SourceFile:91)
	at Ygk.run(SourceFile:102)

[2018-08-08 23:08:38 float-gui-widgets error] :
	java.lang.NoSuchMethodError: com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
	at de.mossgrabers.bitwig.framework.daw.data.SlotImpl.<init>(SlotImpl.java:43)
	at de.mossgrabers.bitwig.framework.daw.data.TrackImpl.<init>(TrackImpl.java:62)
	at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.createTracks(AbstractTrackBankImpl.java:219)
	at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.init(AbstractTrackBankImpl.java:47)
	at de.mossgrabers.bitwig.framework.daw.TrackBankImpl.<init>(TrackBankImpl.java:50)
	at de.mossgrabers.bitwig.framework.daw.ModelImpl.<init>(ModelImpl.java:74)
	at de.mossgrabers.bitwig.framework.BitwigSetupFactory.createModel(BitwigSetupFactory.java:44)
	at de.mossgrabers.controller.apcmini.APCminiControllerSetup.createModel(APCminiControllerSetup.java:94)
	at de.mossgrabers.framework.controller.AbstractControllerSetup.init(AbstractControllerSetup.java:105)
	at de.mossgrabers.bitwig.framework.extension.GenericControllerExtension.init(GenericControllerExtension.java:42)
	at pdf.jwg(SourceFile:19)
	at Zsv.LIa(SourceFile:57)
	at LNJ.Jt2(SourceFile:237)
	at LNJ.EmU(SourceFile:164)
	at LNJ.<init>(SourceFile:127)
	at Ygk.EmU(SourceFile:251)
	at Ygk.eXt(SourceFile:343)
	at Ygk.eXt(SourceFile:202)
	at lx3.run(SourceFile:91)
	at Ygk.run(SourceFile:102)

[2018-08-08 23:08:38 notifications error] APCmini crashed: com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
[2018-08-08 23:08:38 notifications error] APCmini crashed: com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
[2018-08-08 23:08:38 float-gui-widgets error] :
	java.lang.NoSuchMethodError: com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
	at de.mossgrabers.bitwig.framework.daw.data.SlotImpl.<init>(SlotImpl.java:43)
	at de.mossgrabers.bitwig.framework.daw.data.TrackImpl.<init>(TrackImpl.java:62)
	at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.createTracks(AbstractTrackBankImpl.java:219)
	at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.init(AbstractTrackBankImpl.java:47)
	at de.mossgrabers.bitwig.framework.daw.TrackBankImpl.<init>(TrackBankImpl.java:50)
	at de.mossgrabers.bitwig.framework.daw.ModelImpl.<init>(ModelImpl.java:74)
	at de.mossgrabers.bitwig.framework.BitwigSetupFactory.createModel(BitwigSetupFactory.java:44)
	at de.mossgrabers.controller.apcmini.APCminiControllerSetup.createModel(APCminiControllerSetup.java:94)
	at de.mossgrabers.framework.controller.AbstractControllerSetup.init(AbstractControllerSetup.java:105)
	at de.mossgrabers.bitwig.framework.extension.GenericControllerExtension.init(GenericControllerExtension.java:42)
	at pdf.jwg(SourceFile:19)
	at Zsv.LIa(SourceFile:57)
	at LNJ.Jt2(SourceFile:237)
	at LNJ.EmU(SourceFile:164)
	at LNJ.<init>(SourceFile:127)
	at Ygk.EmU(SourceFile:251)
	at Ygk.eXt(SourceFile:343)
	at Ygk.eXt(SourceFile:202)
	at lx3.run(SourceFile:91)
	at Ygk.run(SourceFile:102)
```

**Comment by git-moss** [comment]
Use the branch.

**Comment by git-moss** [comment]
Since it is the only one ;-)
OK, some background: The official version crashes with 2.4 since there is this weird color-class issue, due to an API change (normally this should be backwards compatible but this seems to be a very weird Java issue). You could also use the master and build against API 7, that should also make it work.
Better is to use the branch, which is fully adapted to API 7 (but also does not run in 2.3.5).

**Comment by klingtnet** [comment]
Thank you for the explanation.
