### ISSUE TITLE
Crash with APC40MKII in Bitwig 2.4

### ISSUE THREAD

**Issue by IAmLostForWords** [git-moss/DrivenByMoss#88]
com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
java.lang.NoSuchMethodError: com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
    at de.mossgrabers.bitwig.framework.daw.data.SlotImpl.<init>(SlotImpl.java:43)
    at de.mossgrabers.bitwig.framework.daw.data.TrackImpl.<init>(TrackImpl.java:62)
    at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.createTracks(AbstractTrackBankImpl.java:219)
    at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.init(AbstractTrackBankImpl.java:47)
    at de.mossgrabers.bitwig.framework.daw.TrackBankImpl.<init>(TrackBankImpl.java:50)
    at de.mossgrabers.bitwig.framework.daw.ModelImpl.<init>(ModelImpl.java:74)
    at de.mossgrabers.bitwig.framework.BitwigSetupFactory.createModel(BitwigSetupFactory.java:44)
    at de.mossgrabers.controller.apc.APCControllerSetup.createModel(APCControllerSetup.java:146)
    at de.mossgrabers.framework.controller.AbstractControllerSetup.init(AbstractControllerSetup.java:105)
    at de.mossgrabers.bitwig.framework.extension.GenericControllerExtension.init(GenericControllerExtension.java:42)
    at TD.CAQ(SourceFile:19)
    at zfz.bKU(SourceFile:57)
    at lWS.fMA(SourceFile:237)
    at lWS.OEu(SourceFile:164)
    at lWS.<init>(SourceFile:127)
    at mlO.OEu(SourceFile:251)
    at mlO.mgN(SourceFile:343)
    at mlO.mgN(SourceFile:202)
    at fB.run(SourceFile:91)
    at mlO.run(SourceFile:102)

com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
java.lang.NoSuchMethodError: com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
    at de.mossgrabers.bitwig.framework.daw.data.SlotImpl.<init>(SlotImpl.java:43)
    at de.mossgrabers.bitwig.framework.daw.data.TrackImpl.<init>(TrackImpl.java:62)
    at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.createTracks(AbstractTrackBankImpl.java:219)
    at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.init(AbstractTrackBankImpl.java:47)
    at de.mossgrabers.bitwig.framework.daw.TrackBankImpl.<init>(TrackBankImpl.java:50)
    at de.mossgrabers.bitwig.framework.daw.ModelImpl.<init>(ModelImpl.java:74)
    at de.mossgrabers.bitwig.framework.BitwigSetupFactory.createModel(BitwigSetupFactory.java:44)
    at de.mossgrabers.controller.apc.APCControllerSetup.createModel(APCControllerSetup.java:146)
    at de.mossgrabers.framework.controller.AbstractControllerSetup.init(AbstractControllerSetup.java:105)
    at de.mossgrabers.bitwig.framework.extension.GenericControllerExtension.init(GenericControllerExtension.java:42)
    at TD.CAQ(SourceFile:19)
    at zfz.bKU(SourceFile:57)
    at lWS.fMA(SourceFile:237)
    at lWS.OEu(SourceFile:164)
    at lWS.<init>(SourceFile:127)
    at mlO.OEu(SourceFile:251)
    at mlO.mgN(SourceFile:343)
    at mlO.mgN(SourceFile:202)
    at fB.run(SourceFile:91)
    at mlO.run(SourceFile:102)

**Comment by IAmLostForWords** [comment]
Same goes for Launchpad MKII:

com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
java.lang.NoSuchMethodError: com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
    at de.mossgrabers.bitwig.framework.daw.data.SlotImpl.<init>(SlotImpl.java:43)
    at de.mossgrabers.bitwig.framework.daw.data.TrackImpl.<init>(TrackImpl.java:62)
    at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.createTracks(AbstractTrackBankImpl.java:219)
    at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.init(AbstractTrackBankImpl.java:47)
    at de.mossgrabers.bitwig.framework.daw.TrackBankImpl.<init>(TrackBankImpl.java:50)
    at de.mossgrabers.bitwig.framework.daw.ModelImpl.<init>(ModelImpl.java:74)
    at de.mossgrabers.bitwig.framework.BitwigSetupFactory.createModel(BitwigSetupFactory.java:44)
    at de.mossgrabers.controller.launchpad.LaunchpadControllerSetup.createModel(LaunchpadControllerSetup.java:137)
    at de.mossgrabers.framework.controller.AbstractControllerSetup.init(AbstractControllerSetup.java:105)
    at de.mossgrabers.bitwig.framework.extension.GenericControllerExtension.init(GenericControllerExtension.java:42)
    at TD.CAQ(SourceFile:19)
    at zfz.bKU(SourceFile:57)
    at lWS.fMA(SourceFile:237)
    at lWS.OEu(SourceFile:164)
    at lWS.<init>(SourceFile:127)
    at mlO.OEu(SourceFile:251)
    at mlO.mgN(SourceFile:343)
    at mlO.mgN(SourceFile:202)
    at fB.run(SourceFile:91)
    at mlO.run(SourceFile:102)

com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
java.lang.NoSuchMethodError: com.bitwig.extension.controller.api.ClipLauncherSlot.color()Lcom/bitwig/extension/controller/api/ColorValue;
    at de.mossgrabers.bitwig.framework.daw.data.SlotImpl.<init>(SlotImpl.java:43)
    at de.mossgrabers.bitwig.framework.daw.data.TrackImpl.<init>(TrackImpl.java:62)
    at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.createTracks(AbstractTrackBankImpl.java:219)
    at de.mossgrabers.bitwig.framework.daw.AbstractTrackBankImpl.init(AbstractTrackBankImpl.java:47)
    at de.mossgrabers.bitwig.framework.daw.TrackBankImpl.<init>(TrackBankImpl.java:50)
    at de.mossgrabers.bitwig.framework.daw.ModelImpl.<init>(ModelImpl.java:74)
    at de.mossgrabers.bitwig.framework.BitwigSetupFactory.createModel(BitwigSetupFactory.java:44)
    at de.mossgrabers.controller.launchpad.LaunchpadControllerSetup.createModel(LaunchpadControllerSetup.java:137)
    at de.mossgrabers.framework.controller.AbstractControllerSetup.init(AbstractControllerSetup.java:105)
    at de.mossgrabers.bitwig.framework.extension.GenericControllerExtension.init(GenericControllerExtension.java:42)
    at TD.CAQ(SourceFile:19)
    at zfz.bKU(SourceFile:57)
    at lWS.fMA(SourceFile:237)
    at lWS.OEu(SourceFile:164)
    at lWS.<init>(SourceFile:127)
    at mlO.OEu(SourceFile:251)
    at mlO.mgN(SourceFile:343)
    at mlO.mgN(SourceFile:202)
    at fB.run(SourceFile:91)
    at mlO.run(SourceFile:102)
